spring:
  application:
    name: worker
  datasource: # 数据源配置 (此处用于演示. 实际场景中连接对应业务库, 无需连接调度库)
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/job_flow?characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: develop
    password: develop
    hikari:
      minimum-idle: 5              # 最小空闲连接数
      maximum-pool-size: 20        # 最大连接池数量
      idle-timeout: 60000          # 空闲连接最大存活时间（毫秒）
      max-lifetime: 1800000        # 连接的最大存活时间（毫秒）
      connection-timeout: 30000    # 获取连接的超时时间（毫秒）
      validation-timeout: 5000     # 验证连接的超时时间（毫秒）
      leak-detection-threshold: 2000 # 连接泄露检测的阈值（毫秒）



server:
  port: 8081

vertx-cluster:
  clusterName: job-flow
  port: 5702
  memberList:
    - 127.0.0.1:5701

worker:
  tag: worker
  job-thread-pool:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
    keep-alive-seconds: 60
    thread-name-format: job-worker-%d
